# Source: presto
source @zsh_presto@/init.zsh

# Setup ctrl+left and ctrl+right
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

# Add user binaries
export PATH=$HOME/bin:$PATH

# Enable direnv hook (and export it to path)
eval "$(@direnv@/bin/direnv hook zsh)"
export PATH=@direnv@/bin:$PATH

# Enable local overrides
if [ -f ~/.zshlocal ]; then
    source ~/.zshlocal
fi

