# Using oh my zsh in a non standard location
export ZSH="@oh_my_zsh_home@"

export ZSH_CUSTOM="@oh_my_zsh_custom@"

# Select theme
ZSH_THEME="@oh_my_zsh_theme@"

# Source: oh-my-zsh
source $ZSH/oh-my-zsh.sh
